### ISSUE TITLE
Serde base64 serialization

### ISSUE THREAD

**Issue by daxpedda** [novifinancial/voprf#41]
Is there a reason our implementation of `serde::Serialize` and `serde::Deserialize` are checking for `is_human_readable` and de/encode with base64 in that case? Otherwise I would propose to remove this completely.

**Comment by kevinlewi** [comment]
I believe this was added in here: https://github.com/novifinancial/opaque-ke/pull/168

@nitnelave it should not be necessary to include `is_human_readable` for the serialization and deserialization, right?

**Comment by nitnelave** [comment]
I think it's useful to have: if the protocol is implemented on top of a Json API for instance, base64 is often better. If we're talking about raw bytes, then the encoder/decoder will not be human readable.

What's the motivation for removing the check?

**Comment by daxpedda** [comment]
This should really be solved by the serializer, not by the library implementing the serialization. See https://github.com/serde-rs/json/pull/557, https://github.com/serde-rs/json/issues/360, https://github.com/dtolnay/request-for-implementation/issues/48 and the culmination: https://crates.io/crates/serde-bytes-repr.

The disadvantages of doing it here means that serializers can't handle their own binary encoding format if they like to, if something else for example is desired then base64, but they are human readable, they loose control or have to do de-serialization under the hood again.

Also removing a dependency is always great 😄.

**Comment by nitnelave** [comment]
Well, it does feel like a better solution if we wrap it with the new library. I'm not sure it's gonna be net negative on the dependencies though :) (since the library must depend on base 64, no?)

**Comment by daxpedda** [comment]
> since the library must depend on base 64, no?

It doesn't, no.

**Comment by nitnelave** [comment]
I just realized something: the annotation needs to be in the client code, not in the opake library, right? That would seriously hurt the dev experience, because they suddenly have to know about the serde bytes library and to know to add the annotation. Moreover, in some cases there isn't really a place to add that annotation (if you just pass the OPAQUE message to a generic function that just accepts a serializable, for instance).

In order to have both a good default experience and the possibility to cut the dependency for those who care, how about putting the `is_human_readable` check behind a feature flag that is enabled by default? That way those who care about the dependencies can disable the feature, and the others get the correct behavior by default.

WDYT ?

**Comment by daxpedda** [comment]
Don't get me wrong, I'm all about making libraries as convenient as possible, I love going the extra mile too for it. But I think your feedback is at the wrong place.

A consumer **has** to select the serializer when using our Serde implementation, opaque-ke has nothing to do with the serializer, it only has to give it **correct** information. Base64 is not correct in this case.

I would argue the problem here is serde-json, it seems you believe that the best user experience is provided if binary data is encoded as base64, you should take it up with them. But from the links I provided you above, it seems they are against it.

What we could do is add it to the `serialize` and `deserialize` functions in the high-level API without affecting the Serde implementation. This could also be added behind a crate feature. Personally, I don't think this makes sense, opaque-ke isn't the place to handle serialization preferences.

Anyway, ultimately this is @kevinlewi decision, I'm happy to implement whatever decision we reach here, even if I disagree.

**Comment by nitnelave** [comment]
Right, after looking a bit more into this, I see that the problem is better handled by the serializer.

It's just a bit of a shame then that many web crates make it very easy to use the default Json but a bit harder to use anything else. Oh, well, that's life :)
